# Generated by Django 5.0 on 2023-12-09 10:28

from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Student = apps.get_model("school", "Student")
    for student in Student.objects.all():
        student.teachers.add(student.teacher)
        student.save()


def reverse_func(apps, schema_editor):
    Student = apps.get_model("school", "Student")
    for student in Student.objects.all():
        for teacher in student.teachers.all():
            student.teacher = teacher
        student.save()


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='teachers',
            field=models.ManyToManyField(related_name='students', to='school.teacher'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.CharField(max_length=10, verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.CharField(max_length=10, verbose_name='Предмет'),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
