# Generated by Django 5.0 on 2023-12-09 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_student_teachers_alter_student_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teacher',
        ),
    ]
